ci: formatted workflow yaml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -5,21 +5,20 @@ jobs:
   test:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
-    - uses: actions/setup-python@v4
-      with:
-        python-version: '3.9'
-        cache: 'pip' # caching pip dependencies
-    - name: Install Dependencies
-      run: pip install -r requirements.txt
-    - name: Run Tests
-      run: pytest --junitxml="reports/result.xml"
-    - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()    # run this step even if previous step failed
+      - uses: actions/checkout@v3
+      - uses: actions/setup-python@v4
         with:
-          name: pytest            # Name of the check run which will be created
-          path: reports/result.xml    # Path to test results
-          reporter: java-junit        # Format of test results
+          python-version: "3.9"
+          cache: "pip" # caching pip dependencies
+      - name: Install Dependencies
+        run: pip install -r requirements.txt
+      - name: Run Tests
+        run: pytest --junitxml="reports/result.xml"
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: pytest # Name of the check run which will be created
+          path: reports/result.xml # Path to test results
+          reporter: java-junit # Format of test results
 
-    
